from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch

from ...bootstrap_runtime import bootstrap_runtime

bootstrap_runtime()

from maskrcnn_benchmark.config import cfg
from maskrcnn_benchmark.modeling.detector import build_detection_model
from maskrcnn_benchmark.structures.image_list import to_image_list
from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer


@dataclass
class LegacyVisualBackboneConfig:
    config_file: str
    opts_config_file: str = ""
    weight_file: str = ""
    device: str = "cpu"
    glove_dir: str = ""
    img_dir: str = ""
    roidb_file: str = ""
    dict_file: str = ""
    image_file: str = ""
    conflict_groups_json: str = ""


class LegacyVisualBackboneAdapter:
    def __init__(self, runtime_config: LegacyVisualBackboneConfig) -> None:
        self.runtime_config = runtime_config
        self.model, self.cfg_snapshot = self._load_model()

    def _load_model(self) -> tuple[Any, Any]:
        cfg.merge_from_file(self.runtime_config.config_file)
        if self.runtime_config.opts_config_file:
            cfg.merge_from_file(self.runtime_config.opts_config_file)
        cfg.defrost()
        cfg.MODEL.WEIGHT = self.runtime_config.weight_file
        cfg.MODEL.DEVICE = self.runtime_config.device
        if self.runtime_config.glove_dir:
            cfg.GLOVE_DIR = self.runtime_config.glove_dir
        if self.runtime_config.conflict_groups_json:
            cfg.MODEL.CONFLICT_REENTRY.GROUPS_JSON = self.runtime_config.conflict_groups_json
        cfg.OUTPUT_DIR = str((Path(__file__).resolve().parents[4] / "tmp" / "legacy_visual_runtime").resolve())
        cfg.PATHS_CATALOG = self._build_runtime_paths_catalog(cfg.OUTPUT_DIR)
        cfg.freeze()

        Path(cfg.OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
        model = build_detection_model(cfg)
        model.to(cfg.MODEL.DEVICE)
        model.eval()
        DetectronCheckpointer(cfg, model, save_dir=cfg.OUTPUT_DIR).load(cfg.MODEL.WEIGHT)
        return model, cfg.clone()

    def _build_runtime_paths_catalog(self, output_dir: str) -> str:
        catalog_path = Path(output_dir) / "construction_paths_catalog_runtime.py"
        catalog_path.parent.mkdir(parents=True, exist_ok=True)
        catalog_source = f'''# Auto-generated by scene_graph_service standalone runtime.
import copy


class DatasetCatalog(object):
    DATASETS = {{
        "ConstructionVG_predcls": {{
            "img_dir": r"{self.runtime_config.img_dir}",
            "roidb_file": r"{self.runtime_config.roidb_file}",
            "dict_file": r"{self.runtime_config.dict_file}",
            "image_file": r"{self.runtime_config.image_file}",
        }},
    }}

    @staticmethod
    def get(name, cfg):
        if "VG" in name:
            p = name.rfind("_")
            name, split = name[:p], name[p + 1:]
            assert name in DatasetCatalog.DATASETS and split in {{"train", "val", "test"}}
            args = copy.deepcopy(DatasetCatalog.DATASETS[name])
            args["split"] = split
            args["filter_non_overlap"] = (
                (not cfg.MODEL.ROI_RELATION_HEAD.USE_GT_BOX)
                and cfg.MODEL.RELATION_ON
                and cfg.MODEL.ROI_RELATION_HEAD.REQUIRE_BOX_OVERLAP
            )
            args["filter_empty_rels"] = cfg.MODEL.RELATION_ON
            args["flip_aug"] = cfg.MODEL.FLIP_AUG
            args["custom_eval"] = cfg.TEST.CUSTUM_EVAL
            args["custom_path"] = cfg.TEST.CUSTUM_PATH
            args["num_im"] = cfg.DATASETS.debug_num_im
            args["num_val_im"] = cfg.DATASETS.debug_num_val_im
            return dict(factory="VGDataset", args=args)
        raise RuntimeError("Dataset not available: {{}}".format(name))


class ModelCatalog(object):
    @staticmethod
    def get(name):
        raise RuntimeError("ModelCatalog is not used in standalone runtime: {{}}".format(name))
'''
        # Keep the generated catalog stable across tasks.  Rewriting an
        # identical file changes its mtime and can spuriously trigger file
        # watchers in development servers.
        if not catalog_path.exists() or catalog_path.read_text(encoding="utf-8") != catalog_source:
            catalog_path.write_text(catalog_source, encoding="utf-8")
        return str(catalog_path)

    @property
    def device(self) -> torch.device:
        return torch.device(self.cfg_snapshot.MODEL.DEVICE)

    def extract_backbone_features(self, image_tensor: torch.Tensor) -> list[torch.Tensor]:
        with torch.no_grad():
            image_list = to_image_list(
                [image_tensor.to(self.device)],
                size_divisible=int(self.cfg_snapshot.DATALOADER.SIZE_DIVISIBILITY),
            )
            features = self.model.backbone(image_list.tensors)
        if isinstance(features, torch.Tensor):
            return [features]
        return list(features)
